source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Forca' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forca
  pod 'SnapKit', '~> 5.6.0'

  target 'ForcaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ForcaUITests' do
    # Pods for testing
  end

end
