# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'github-repositories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github-repositories

  target 'github-repositoriesTests' do
    pod 'SnapKit', '~> 5.0.0'
  end

  target 'github-repositoriesUITests' do
    # Pods for testing
  end

end
